### ISSUE TITLE
Error after building binding

### ISSUE THREAD

**Issue by therrymart** [KristinHansen/Functions-From-Query#1]
Hi there, followed your direction and walked through your demo.

getting an error with binding
The xxxxxxxxxxxxxx' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'xxxxxxxxxxxxxx'. Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'ids' to type List`1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).

build exactly as per teh demo but adjusted to the project context
Any ideas?

**Comment by KristinHansen** [comment]
The error seems to suggest that the `FromQuery` binding extension hasn't been registered correctly.

Are you using static functions or have you used DI as the demo?
If the latter is the case, could you copy/paste your startup class, as it might be an issue with the registration, particularly the following:
```csharp
public class WebJobsStartup : IWebJobsStartup
{
    public void Configure(IWebJobsBuilder builder)
    {
        builder.AddFromQueryExtension();
    }
}
```

Also, did you decorate the namespace with `[assembly: WebJobsStartup(typeof(YourNameSpace.WebJobsStartup))]`?
Should look something like this:
```csharp
[assembly: WebJobsStartup(typeof(Eli.Azure.Functions.Test.WebJobsStartup))]
namespace Eli.Azure.Functions.Test
{
    public class WebJobsStartup : IWebJobsStartup
    {
        ...
```

**Comment by therrymart** [comment]
Hi there, below is the Startup.cs extract. Also note the error now being displayed after I adjusted the FromQueryAttribute..

The name of " list<string> id " is what i'm looking to bind into the function. All I want is to bring the list<string> into the function so I can use it in a mongodb method

![2021-03-22_11-30-08](https://user-images.githubusercontent.com/37013336/111968675-172db900-8b02-11eb-8b8f-d5126ba1d36a.png)

[assembly: FunctionsStartup(typeof(BaseUser.Mongo.APIs.FunctionStartup))]
[assembly: WebJobsStartup(typeof(BaseUser.Mongo.APIs.WebJobsStartup))]
namespace BaseUser.Mongo.APIs
{

    public class ConverterOptions
    {
        public IEnumerable<IStringValueConverter> Converters { get; set; } = new List<IStringValueConverter>();
    }

    public static class FromQueryExtensions
    {
        public static IWebJobsBuilder AddFromQueryExtension(this IWebJobsBuilder builder)
        {
            builder.AddExtension<FromQueryConfigProvider>();

            builder.Services
                .AddTransient<IStringValueConverter, GuidConverter>()
                .AddTransient<IStringValueConverter, IntConverter>()
                .AddTransient<FromQueryBinding>()
                .AddTransient<FromQueryBindingProvider>()
                .AddTransient<FromQueryValueProvider>();

            return builder;
        }
    }
    public class WebJobsStartup : IWebJobsStartup
    {
        public void Configure(IWebJobsBuilder builder)
        {

            builder.AddJwtBindingExtension();


            builder.AddFromQueryExtension();

            //   builder.AddExtension<FromQueryConfigProvider>();


        }
    }

    public class FunctionStartup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            ConfigureServices(builder.Services);

            builder.Services.AddHttpClient();

            builder.Services.AddLogging(loggingBuilder =>
            {
                loggingBuilder.AddFilter(level => true);
            });


            var config = (IConfiguration)builder.Services.First(d => d.ServiceType == typeof(IConfiguration)).ImplementationInstance;

            builder.Services.AddSingleton((s) =>
            {
                MongoClient client = new MongoClient(System.Environment.GetEnvironmentVariable("MONGO_CONNECTION_STRING"));

                return client;
            });

            builder.Services.AddAuth0Authentication();

        }


        public void ConfigureServices(IServiceCollection services)
        {
            services.AddAutoMapper(typeof(FunctionStartup));
            services.AddSingleton<IManagementConnection, HttpClientManagementConnection>();
            services.AddSingleton<IAuthenticationConnection, HttpClientAuthenticationConnection>();


        }
    
    }
}

**Comment by therrymart** [comment]
FYI its list<string> id that I intend pulling into the function

**Comment by KristinHansen** [comment]
I see what the issue is. The `AddFromQueryExtension` is missing a few registrations:
```csharp
builder.Services
    .Configure(action)
    .AddTransient<IStringValueConverter, GuidConverter>()
    .AddTransient<IStringValueConverter, IntConverter>()
    .AddTransient<FromQueryBindingProvider>()
    .AddTransient<FromQueryBindingFactory>()
    .AddTransient<FromQueryBinding>()
    .AddTransient<FromQueryValueProviderFactory>()
    .AddTransient<FromQueryValueProvider>();
```

I think I mentioned it in the original answer on SO. The factories are there to ensure that the `FromQuery` binding can be used multiple times. This is due to the lifetime of the `FromQueryConfigProvider` and `FromQueryBindingProvider` being singletons. I know it's confusing when `FromQueryBindingProvider` is added as transient. This is because there is a "binding provider provider" of sorts, that will get all implementations of `IBindingProvider`. This provider is most likely singleton. Because of this, without the factories, we'd be reusing the same binding across all bindings of `FromQuery`; two different functions would use the exact same binding, and thus, would need the same signature to work, which would limit its usefulness dramatically, obiviously.

I'll look into adding this to NuGet as a package instead. Should allow you to simply add the package as a dependency and invoke `AddFromQueryExtension` without duplicating the original code.

**Comment by therrymart** [comment]
Stop on bud!!!!
Working now and all is well. Thanks for everything and especially the speedy replies!

**Comment by KristinHansen** [comment]
Glad you got it working. Will publish a NuGet package soonish.

**Comment by KristinHansen** [comment]
@therrymart 
The NuGet package is now available. See the readme for package id.
Also made a few improvements. The sample project has been updated as well, showing how it's used.
